var musicLise = {
	music1:{
		"name":"断桥残雪",
		"autor":"许嵩",
		"img":"duanqiaocanxue",
		"times":"04:30"
	},
	music2:{
		"name":"认错",
		"autor":"许嵩",
		"img":"rencuo",
		"times":"04:30"
	},
	music3:{
		"name":"天使",
		"autor":"许嵩",
		"img":"tianshi",
		"times":"04:30"
	},
	music4:{
		"name":"对话老师",
		"autor":"许嵩",
		"img":"duihualaoshi",
		"times":"04:30"
	},
	music5:{
		"name":"素颜",
		"autor":"许嵩",
		"img":"suyan",
		"times":"04:30"
	},
	music6:{
		"name":"红妆",
		"autor":"徐良",
		"img":"hongzhuang",
		"times":"04:30"
	},
	music7:{
		"name":"后会无期",
		"autor":"徐良&&汪苏泷",
		"img":"houhuiwuqi",
		"times":"04:30"
	},
	music8:{
		"name":"忘情水",
		"autor":"刘德华",
		"img":"wangqingshui",
		"times":"04:30"
	},
	music9:{
		"name":"忘情水",
		"autor":"刘德华",
		"img":"wangqingshui",
		"times":"04:30"
	},
	music10:{
		"name":"对话老师",
		"autor":"许嵩",
		"img":"duihualaoshi",
		"times":"04:30"
	},
	music11:{
		"name":"素颜",
		"autor":"许嵩",
		"img":"suyan",
		"times":"04:30"
	},
	music12:{
		"name":"红妆",
		"autor":"徐良",
		"img":"hongzhuang",
		"times":"04:30"
	},
	music13:{
		"name":"后会无期",
		"autor":"徐良&&汪苏泷",
		"img":"houhuiwuqi",
		"times":"04:30"
	},
	music14:{
		"name":"忘情水",
		"autor":"刘德华",
		"img":"wangqingshui",
		"times":"04:30"
	}
};